import type { Metadata } from "next";
import {
  //  Inter,
  Rubik,
} from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar";

// Fonts
// const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
